### ISSUE TITLE
Question about requirements

### ISSUE THREAD

**Issue by TCPuniverse** [rdoxenham/openshift-virt-labs#10]
Hello;
You've mentioned using SSD and NVMe as the requirements. I have only HDDs on my ESXi server. If I were to follow this guide to build a small OKD lab, should I expect for the install script to finish successfully? I don't mind any performance issues, because this is going to be a training lab for me. 
And, have you hard-coded VM requirements in the script? I don't have 128 Gb of RAM, So I will try to adjust the VM properties to be as minimum as possible.

**Comment by rdoxenham** [comment]
@TCPuniverse hey, thanks for raising this... it *may* work for you, but I suspect you'll run into a lot of issues due to I/O limitations on spinning disks. You'll also likely run into challenges with memory availability. How much memory do you have?

**Comment by TCPuniverse** [comment]
Hello; Thanks for your reply. Our ESXi server in office has 96Gb of RAM, but The server is used by other people as well, therefor I should wait for the time others shut down their VMs so I can create the lab. Most probably I can use something close to 50~55 Gb of ram at nights when nobody actively uses the server. The amount of CPU is not important, but there are only HDDs installed on the server. I'm completely newbie, even pre-newbie to this world, so I just want to have a working lab to play with. a month ago I installed Minishift, but its version was too old and I stuck where what I read on the books/guides, wasn't exist on the Minishift.

**Comment by rdoxenham** [comment]
@TCPuniverse sorry for the slow response. This script requires direct baremetal access to a physical system, so you'd need to uninstall ESX and install RHEL/CentOS/Fedora on it, which I am not suggesting you do if this is part of a cluster. If you want to run through this you may want to consider a different system.

**Comment by rdoxenham** [comment]
Closing this for now, please do re-open if you need more help :-)
