### ISSUE TITLE
Can't get images from register, Could you help take a look? Thanks.

### ISSUE THREAD

**Issue by imicer** [rdoxenham/openshift-virt-labs#11]
Hello

I tired to run install.sh in bare meter environment, this env meets the requirements mentoned in doc.
when runing deploy-disconnected.sh, there was error message as below:

error: unable to connect to ocp4-bastion.cnv.example.com:5000/ocp4/openshift4: Get "https://ocp4-bastion.cnv.example.com:5000/v2/": Service Unavailable
error: unable to connect to ocp4-bastion.cnv.example.com:5000/ocp4/openshift4: Get "https://ocp4-bastion.cnv.example.com:5000/v2/": Service Unavailable
error: unable to connect to ocp4-bastion.cnv.example.com:5000/ocp4/openshift4: Get "https://ocp4-bastion.cnv.example.com:5000/v2/": Service Unavailable
error: unable to connect to ocp4-bastion.cnv.example.com:5000/ocp4/openshift4: Get "https://ocp4-bastion.cnv.example.com:5000/v2/": Service Unavailable
error: unable to connect to ocp4-bastion.cnv.example.com:5000/ocp4/openshift4: Get "https://ocp4-bastion.cnv.example.com:5000/v2/": Service Unavailable
error: unable to connect to ocp4-bastion.cnv.example.com:5000/ocp4/openshift4: Get "https://ocp4-bastion.cnv.example.com:5000/v2/": Service Unavailable

It seemed the docker register can't mirror into local. but I still contiune to install, when steping into starting bootstrap, there is the following error happening, coudl you please help take a look? Thanks.

Mar 04 15:14:21 ocp4-bootstrap.cnv.example.com release-image-download.sh[1652]: Error: error pulling image "quay.io/openshift-release-dev/ocp-release@sha256:47df4bfe1cfd6d63dd2e880f00075ed1d37f997fd54884ed823ded9f5d96abfc": unable to pull quay.io/openshift-release-dev/ocp-release@sha256:47df4bfe1cfd6d63dd2e880f00075ed1d37f997fd54884ed823ded9f5d96abfc: unable to pull image: Error initializing source docker://quay.io/openshift-release-dev/ocp-release@sha256:47df4bfe1cfd6d63dd2e880f00075ed1d37f997fd54884ed823ded9f5d96abfc: (Mirrors also failed: [ocp4-bastion.cnv.example.com:5000/ocp4/openshift4@sha256:47df4bfe1cfd6d63dd2e880f00075ed1d37f997fd54884ed823ded9f5d96abfc: error pinging docker registry ocp4-bastion.cnv.example.com:5000: Get "https://ocp4-bastion.cnv.example.com:5000/v2/": dial tcp 192.168.123.100:5000: connect: no route to host]): quay.io/openshift-release-dev/ocp-release@sha256:47df4bfe1cfd6d63dd2e880f00075ed1d37f997fd54884ed823ded9f5d96abfc: error pinging docker registry quay.io: Get "https://quay.io/v2/": dial tcp: lookup quay.io on 192.168.123.100:53: server misbehaving

**Comment by rdoxenham** [comment]
Hey @imicer looks like your registry didn't come up as expected, but it also looks like you're having some DNS issues. Can you cleanup and retry the install to see if you get the same results? Thanks!

**Comment by rdoxenham** [comment]
Closing this for now, please do re-open if you need more help :-)
